### ISSUE TITLE
Ramp up metric operationalization

### ISSUE THREAD

**Issue by maxmichalec** [maxmichalec/461-project-9#13]
**Description**: Look at the README/any other documentation to see the length of it. This metric will be calculated based on the length of the documentation that the module has.
**Implementation**: Clone in GitHub repo and use README length to determine score [0,1]

**Comment by mnarnold** [comment]
This has been done, although it could be optimized.  I would say this is done, and then if there is extra time at the end of the project, we can try to optimize it more.
